kind: pipeline
type: docker
name: wlts-qgis

steps:
- name: build
  image: qgis/qgis:release-3_16
  commands:
  - pip3 install --upgrade pip
  - pip3 install --upgrade setuptools
  - pip3 install -e .[tests,docs]
  - ./run-tests.sh

- name: coverage
  image: plugins/codecov
  settings:
    files:
    - coverage.xml
    - .coverage
    token:
      from_secret: codecov_token
  when:
    event:
    - push

# - name: discord-notify
#   image: brazildatacube/bdc-drone-discord
#   settings:
#     webhook:
#       from_secret: discord_webhook
#   when:
#     status:
#       - failure
#       - success